ElizaPopa/SM-TM-7b3e6_loading_spinner
SkillBrain-com/Calisto-g1-15-05-22-internship-xretech pull request #10
Opened 2022-10-11 20:39 UTC by ElizaPopa

2022-10-13 04:32 UTC, 95teo requested changes

2022-10-13 04:32 UTC, 95teo commented on src/main/java/pages/LoadingSpinnerPage.java
> +    LoginPage loginPage;
You shouldn't need loginPage here. Please remove it. Thanks!

2022-10-13 04:32 UTC, 95teo commented on src/main/java/pages/LoadingSpinnerPage.java
> +        elementControl.clickElement(loginAsEndUserButton);
Please move login steps to test case itself and try to avoid using pages inside other pages. It can cause some circular dependencies. Thanks!

2022-10-14 06:15 UTC, 95teo requested changes

2022-10-14 06:15 UTC, 95teo commented on src/main/java/pages/LoadingSpinnerPage.java
> +
No need to leave this blank line at the beginning of the method. Can you please remove it? Applicable for all other methods. Thanks!

2022-10-14 06:15 UTC, 95teo commented on src/main/java/pages/LoadingSpinnerPage.java
> +
Please remove one blank line. Thanks!

2022-10-14 06:15 UTC, 95teo commented on src/main/java/utils/JavascriptUtils.java
> +
No need for this blank line here. Thanks!

2022-10-14 06:15 UTC, 95teo commented on src/main/java/utils/JavascriptUtils.java
> +    public void executeScriptToElement(WebElement element) {
Please add a String script argument to method in order to be able to be used with other scripts too. Thanks!

2022-10-14 06:15 UTC, 95teo commented on src/test/java/loadingSpinner/Tests.java
> +        loginPage.login(userCredential.getUsername(), userCredential.getPassword());
You can use the following method for logging in -> loginPage.loginWithCredentials(configProperty.getProperty(ConfigPropertiesEnum.USERNAME_ADMIN_XRETECH.label),
                configProperty.getProperty(ConfigPropertiesEnum.PASSWORD_ADMIN_XRETECH.label));
There is no real advantage in having multiple login methods. Thanks!

2022-10-14 06:15 UTC, 95teo commented on src/main/java/pages/LoginPage.java
> +    public void loginAsAdmin(String username, String password) {
No need to add this loginAsAdmin method. You can use loginWithCredentials instead. Thanks!

2022-10-14 06:15 UTC, 95teo commented on src/main/java/pages/LoginPage.java
>      public void login(String username, String password) {
We'll try to deprecate this login method and use loginWithCredentials instead. Thanks!

2022-10-14 09:25 UTC, ElizaPopa commented on src/main/java/pages/LoadingSpinnerPage.java
> +
I don't understand which line? If i use reformat line, all methods are automatically arranged with blank line between one another or between steps and the name of method.

2022-10-14 09:28 UTC, ElizaPopa commented on src/main/java/utils/JavascriptUtils.java
> +    public void executeScriptToElement(WebElement element) {
done

2022-10-14 09:29 UTC, 95teo commented on src/main/java/pages/LoadingSpinnerPage.java
> +
The blank line between methods it's fine. I was referring to the line between name of the method and step. On my case it's not putting that line at reformat code.

2022-10-14 09:35 UTC, ElizaPopa commented on src/test/java/loadingSpinner/Tests.java
> +        loginPage.login(userCredential.getUsername(), userCredential.getPassword());
Ok, i've changed in both tests: Admin + Support. Also i rename the labels....with the right form Xreteh instead of Xretech.

2022-10-14 09:38 UTC, ElizaPopa commented on src/main/java/pages/LoginPage.java
> +    public void loginAsAdmin(String username, String password) {
I understand what you say, I tried to be as precise as possible because in the tests I am logged in both as admin and as support, but I deleted my method.

2022-10-14 09:44 UTC, ElizaPopa commented on src/main/java/pages/LoginPage.java
>      public void login(String username, String password) {
I've changed in all tests with loginWithCredentials and deleted the login one.

2022-10-14 09:51 UTC, ElizaPopa commented on src/main/java/pages/LoadingSpinnerPage.java
> +
I've deleted the line between name of the method and steps. Please check all task. I've made a new commit + push.

2022-10-14 10:01 UTC, 95teo commented on src/main/java/pages/LoginPage.java
> +    public void loginAsAdmin(String username, String password) {
Sure. No problem. But we are sending them in test case as enum constants and we can figure it out from there what kind of role we are using ;)

2022-10-14 10:02 UTC, 95teo requested changes

2022-10-14 10:02 UTC, 95teo commented on src/test/java/loadingSpinner/Tests.java
> +    @Test
It's ok to leave one blank line between methods as you did in the page class. Thanks!

2022-10-14 19:58 UTC, stanciuvlad99 commented on src/main/java/pages/LoginPage.java
Delete the blank from 37. Thank you!

2022-10-15 15:57 UTC, 95teo approved these changes

2022-10-15 18:14 UTC, stanciuvlad99 approved these changes

2022-10-15 18:14 UTC, stanciuvlad99 commented on src/main/java/pages/LoginPage.java
> +
Delete the blank space 37. Thank you!

2022-10-15 18:20 UTC, ElizaPopa commented on src/main/java/pages/LoginPage.java
done

2022-10-15 18:21 UTC, ElizaPopa commented on src/main/java/pages/LoginPage.java
> +    }
I have already. Thank you too!

2022-10-15 18:25 UTC, merged