Stanciu vlad/sm tm dfb63 define custom fields
SkillBrain-com/Calisto-g1-15-05-22-internship-xretech pull request #11
Opened 2022-10-12 13:28 UTC by stanciuvlad99

define custom fields

2022-10-13 11:35 UTC, 95teo requested changes

2022-10-13 11:35 UTC, 95teo commented on src/main/java/pages/DefineCustomFieldsForCategoriesPage.java
> +    public void clickOnCustomFiledsButton() {
Please move methods after WebElements meaning that you first will put WebElements grouped and then the methods after WebElements. Thanks!

2022-10-13 11:35 UTC, 95teo commented on src/main/java/pages/DefineCustomFieldsForCategoriesPage.java
> +    public void clickOnDropdownOprionsFieldAndSelect() {
Typo in the name of the method -> Options

2022-10-13 11:35 UTC, 95teo commented on src/main/java/pages/ManageDefaultSubscriptionsPage.java
> -package pages;
Why have you removed this page? It was merged in your previous PR in main. Please revert this change. Thanks!

2022-10-13 11:35 UTC, 95teo commented on src/test/java/xertechTests/ManageDefaultSubscriptionsTest.java
> -package xertechTests;
Why have you removed this page? It was merged in your previous PR in main. Please revert this change. Thanks!

2022-10-13 11:35 UTC, 95teo commented on target/maven-status/maven-compiler-plugin/compile/default-compile/createdFiles.lst
>  implementation\BrowserManager.class
Try to avoid checking-in files from target, idea or target-output folders. Thanks!

2022-10-13 11:35 UTC, 95teo commented on src/test/java/xertechTests/DefineCustomFieldsForCategoriesTest.java
> +    public void AddANewCustomField(){
camelCase for method names

2022-10-14 09:53 UTC, 95teo requested changes

2022-10-14 09:53 UTC, 95teo commented on src/main/java/pages/DefineCustomFieldsForCategoriesPage.java
> +    public void Options() {
Please give a more meaningful name to this method and use camelCase as per Java conventions when naming methods. Thanks!

2022-10-14 09:53 UTC, 95teo commented on src/main/java/pages/ManageDefaultSubscriptionsPage.java
> -package pages;
Please add back this class.

2022-10-14 10:16 UTC, 95teo commented on src/main/java/pages/DefineCustomFieldsForCategoriesPage.java
> +    public String getCurrentUrl() {
You already have this method in BasePage. Why putting in here too?

2022-10-14 10:17 UTC, 95teo commented on src/test/java/manageDefaultSubscriptions/ManageDefaultSubscriptionsTest.java
> +                configProperty.getProperty(ConfigPropertiesEnum.USERNAME_ADMIN_XRETEH.label));
PASSWORD_ADMIN_XRETECH for this row.

2022-10-14 10:17 UTC, 95teo commented on src/test/java/manageDefaultSubscriptions/ManageDefaultSubscriptionsTest.java
> +                configProperty.getProperty(ConfigPropertiesEnum.USERNAME_ADMIN_XRETEH.label));
PASSWORD_ADMIN_XRETECH for this row.

2022-10-14 10:24 UTC, 95teo approved these changes

2022-10-14 11:29 UTC, 95teo approved these changes

2022-10-14 17:49 UTC, ElizaPopa commented
Please check your tests. You have 2 failed.

![Screen Shot 2022-10-14 at 8 43 14 PM](https://user-images.githubusercontent.com/109477059/195909569-48a8671c-e422-44e6-9c20-2d7c69507e74.png)

2022-10-14 17:51 UTC, ElizaPopa commented
Did you want to say fields here? If yes, please rename them. Thanks

![Screen Shot 2022-10-14 at 8 50 36 PM](https://user-images.githubusercontent.com/109477059/195909899-003e9dbb-2f77-4751-8a7b-b6b568b9f8e8.png)

2022-10-14 17:53 UTC, ElizaPopa commented
If you want, you can also rename your package tests: "XretehTests" instead of "xertechTests".

2022-10-14 17:56 UTC, ElizaPopa commented
In your public class DefineCustomFieldsForCategoriesPage, wouldn't be better if you put first all the elements and after all of these, your methods? I've noticed you have one WebElement...one method. I don't know if you discuss this part with Teofil already.

2022-10-14 19:45 UTC, ElizaPopa commented on src/test/java/defineCustomFieldsForCategories/Base.java
> +
Please delete these empty rows.

2022-10-14 19:48 UTC, ElizaPopa approved these changes

2022-10-14 19:48 UTC, ElizaPopa commented on src/test/java/defineCustomFieldsForCategories/Base.java
> +
Also here

2022-10-15 16:00 UTC, 95teo approved these changes

2022-10-15 16:46 UTC, merged