Pista_Marcel_SM_TM_5317_I_want_to_be_able_to_assign_a_model_to_Client…
SkillBrain-com/Calisto-g1-15-05-22-internship-xretech pull request #12
Opened 2022-10-15 16:23 UTC by pistamarcel

Pista_Marcel_SM_TM_5317_I_want_to_be_able_to_assign_a_model_to_Clients_and_Endusers first draft

2022-10-16 15:37 UTC, 95teo requested changes

2022-10-16 15:37 UTC, 95teo commented on src/main/java/pages/AssignAModelToClientsAndEndUsersPage.java
> +public class AssignAModelToClientsAndEndUsersPage extends BasePage {
Can you please rename the class to AssignModelPage? Thanks!

2022-10-16 15:37 UTC, 95teo commented on src/main/java/pages/AssignAModelToClientsAndEndUsersPage.java
> +        Thread.sleep(1000);
Can you please replace Thread.sleep() occurrences from this class with some new/existing methods from WaitUtils that will use FluentWait? For example, waitForElementToBePresent/Visible, waitForElementToBeInteractable. Let me know if you need more guidance. Thanks!

2022-10-16 15:37 UTC, 95teo commented on src/test/java/assignAModelTo/AssignAModelToClientsAndEndUsersTest.java
> +                Thread.sleep(1000);
Can we replace these Thread.sleep() occurrences with methods that use FluentWait behind? Thanks!

2022-10-16 15:37 UTC, 95teo commented on src/test/java/assignAModelTo/AssignAModelToClientsAndEndUsersTest.java
> +        if (client) {
It's not recommended to have this logic at test level. Let's make separate scenarios for each of the if-else code branches. You can use some dataProviders for username/password maybe in order not to hardcode them in every test case. Thanks!

2022-10-17 09:12 UTC, 95teo commented on src/test/java/assignAModelTo/AssignAModelToClientsAndEndUsersTest.java
> +        if (client) {
To be honest I don't like what I hear ... that means that your tests depend on each other and are not independent ... Can we have different models for each test case? Is it duable? Thanks! ;)

2022-10-28 12:15 UTC, 95teo requested changes

2022-10-28 12:15 UTC, 95teo commented on src/main/java/pages/AssignModelPage.java
> +    @FindBy(css = "li.rounded-lg.mb-2 a[href='/clients']")
Please leave a blank line above in order to separate a bit @FindBy section from String declaration section. Thanks!

2022-10-28 12:15 UTC, 95teo commented on src/main/java/pages/AssignModelPage.java
> +        WaitUtils waitUtils = new WaitUtils(driver);
Try to put this line with initialization WaitUtils waitUtils = new WaitUtils(driver); as a member in the class and not in every method that it's used.

2022-10-28 12:15 UTC, 95teo commented on src/main/java/pages/AssignModelPage.java
> +
Remove this line. Thanks!

2022-10-28 12:15 UTC, 95teo commented on src/main/java/utils/WaitUtils.java
> +    public void waitForElementToBeLessThan(By locator, Integer number) {
Please leave a blank line between methods. Thanks!

2022-10-28 12:15 UTC, 95teo commented on src/test/java/assignAModelTo/AssignAModelFromAdmin.java
> +        WaitUtils waitUtils = new WaitUtils(driver);
Put this line with initialization of WaitUtils inside Base test class and remove it from this class. Thanks!

2022-10-28 12:15 UTC, 95teo commented on src/test/java/assignAModelTo/AssignAModelFromAdmin.java
> +        ;
Do you miss a line here? If not, please remove line with ';' Thanks!

2022-10-28 12:15 UTC, 95teo commented on src/test/java/assignAModelTo/AssignAModelFromAdmin.java
> +
Remove on line from here, please!

2022-10-28 12:15 UTC, 95teo commented on src/test/java/assignAModelTo/AssignAModelFromAdmin.java
> +
Leave only one blank line here. Thanks!

2022-10-28 12:15 UTC, 95teo commented on src/test/java/assignAModelTo/AssignAModelFromSupport.java
> +        WaitUtils waitUtils = new WaitUtils(driver);
Put this line with initialization of WaitUtils inside Base test class and remove it from this class. Thanks!

2022-10-28 12:15 UTC, 95teo commented on src/test/java/assignAModelTo/AssignAModelFromSupport.java
> +
Leave only one blank line here. Thanks!

2022-10-28 12:15 UTC, 95teo commented on src/test/java/assignAModelTo/AssignAModelFromSupport.java
> +
Leave only one blank line here. Thanks!

2022-10-29 18:04 UTC, 95teo approved these changes

2022-10-31 12:21 UTC, 95teo commented
Please fix conflicts first. Thanks!

2022-11-02 07:16 UTC, 95teo approved these changes

2022-11-02 10:00 UTC, stanciuvlad99 approved these changes

2022-11-02 10:00 UTC, stanciuvlad99 commented on src/test/java/assignAModelTo/Base.java
> +
Delete the blank space. Thank you!

2022-11-02 11:39 UTC, merged