Stanciu Vlad/sm tm 58f91 as a client able to generate a link
SkillBrain-com/Calisto-g1-15-05-22-internship-xretech pull request #14
Opened 2022-10-31 10:39 UTC by stanciuvlad99

2022-11-02 07:26 UTC, 95teo requested changes

2022-11-02 07:26 UTC, 95teo commented on src/main/java/pages/BasePage.java
> +    static WebDriver driver = null;
Please revert this change as it's not needed. You can use the page that you're on your tests cases. Thanks!

2022-11-02 07:26 UTC, 95teo commented on src/main/java/pages/BasePage.java
> +    public static String getCurrentUrl(){
Please revert this change as it's not needed. You can use the page that you're on your tests cases. Thanks!

2022-11-02 07:26 UTC, 95teo commented on src/main/java/utils/enums/ConfigPropertiesEnum.java
> +        USERNAME_ADMIN_XRETECH("usernameAdminXreteh"),
Why have you made this renaming? The name is XRETEH and not XRETECH on the site. Please revert it.

2022-11-02 07:26 UTC, 95teo commented on src/test/java/clientGenerateALink/Base.java
> +//    @AfterMethod
Why have you left this method commented? It won't close the browser a test case is run. Please uncomment it. Thanks!

2022-11-02 07:26 UTC, 95teo commented on src/test/java/clientGenerateALink/Base.java
> +    protected FluentWait<WebDriver> fluentWait(WebDriver driver) {
Please remove this method from here. We have a WaitUtils class where we handle waits. Thanks!

2022-11-02 07:26 UTC, 95teo commented on src/test/java/manageDefaultSubscriptions/ManageDefaultSubscriptionsTest.java
> +package xertechTests;
Please leave manageDefaultSubscriptions as package name. Thanks!

2022-11-02 07:26 UTC, 95teo commented on src/test/java/clientGenerateALink/clientGenerateALinkTest.java
> +        assertTrue(BasePage.getCurrentUrl().contains("/my-account"),
Please use clientGenerateALinkPage instead of BasePage for all occurrences in this class. Thanks!

2022-11-02 10:08 UTC, ElizaPopa approved these changes

2022-11-02 10:08 UTC, ElizaPopa commented on src/main/java/pages/ClientGenerateALinkPage.java
> +
Please delete this blank line. Thank you!

2022-11-02 10:08 UTC, ElizaPopa commented on src/main/java/pages/ClientGenerateALinkPage.java
> +
Please delete this blank line. Thank you!

2022-11-02 10:08 UTC, ElizaPopa commented on src/test/java/clientGenerateALink/Base.java
> +
Please delete this blank line. Thank you!

2022-11-02 10:08 UTC, ElizaPopa commented on src/test/java/clientGenerateALink/Base.java
> +
Please delete this blank line. Thank you!

2022-11-02 10:08 UTC, ElizaPopa commented on src/test/java/clientGenerateALink/ClientGenerateALinkTest.java
> +
Please delete this blank line. Thank you!

2022-11-02 11:32 UTC, pistamarcel reviewed
I don't have a problem with blank lines, especially at the end of the file. I was just wondering why use FluenWait in the first place since you have it in Utils.
That's all. Great job!

2022-11-02 11:34 UTC, pistamarcel approved these changes

2022-11-03 07:56 UTC, 95teo commented
Please fix the conflicts too. Thanks!

2022-11-03 10:37 UTC, stanciuvlad99 commented
> I don't have a problem with blank lines, especially at the end of the file. I was just wondering why use FluenWait in the first place since you have it in Utils. That's all. Great job!

Solved it.

2022-11-04 06:16 UTC, 95teo approved these changes

2022-11-04 09:02 UTC, merged