Eliza popa/sm tm f26cf assign clients from the model
SkillBrain-com/Calisto-g1-15-05-22-internship-xretech pull request #15
Opened 2022-11-02 11:53 UTC by ElizaPopa

2022-11-03 08:07 UTC, 95teo requested changes

2022-11-03 08:07 UTC, 95teo commented on src/main/java/pages/ModelsPage.java
> +        jsUtils.executeScriptToElement("arguments[0].scrollIntoView();", lastClientFromTheDropList);
Can you please add a constant for this script and use it instead of the hardcoded string? You can define the constant even in the JavascriptUtils class. Thanks!

2022-11-03 08:07 UTC, 95teo commented on src/test/java/AssigningModels/Tests.java
> +        loginPage.loginWithCredentials(configProperty.getProperty(ConfigPropertiesEnum.USERNAME_ADMIN_XRETEH.label),
If you're using the properties from config file you don't need the lines with generator. So, you either use the generator approach or reading from config file. Please choose only one approach and use it for all of the test cases from this file. Thanks!

2022-11-03 08:07 UTC, 95teo commented on src/test/java/loadingSpinner/Tests.java
> +//        loginPage.loginAsEndUser();
Why is this line commented?

2022-11-03 10:07 UTC, ElizaPopa commented on src/main/java/pages/ModelsPage.java
> +        jsUtils.executeScriptToElement("arguments[0].scrollIntoView();", lastClientFromTheDropList);
Done.

2022-11-03 10:20 UTC, ElizaPopa commented on src/test/java/loadingSpinner/Tests.java
> +//        loginPage.loginAsEndUser();
I forgot to undo this comment line. It was commented at that time with compound class error. Now all good.

2022-11-03 10:40 UTC, stanciuvlad99 approved these changes

2022-11-03 10:40 UTC, stanciuvlad99 commented on src/main/java/pages/ModelsPage.java
> +
Delete the blank space. Thank you!

2022-11-03 10:40 UTC, stanciuvlad99 commented on src/main/java/pages/ModelsPage.java
> +
Delete the blank space. Thank you!

2022-11-03 10:40 UTC, stanciuvlad99 commented on src/main/java/pages/ModelsPage.java
> +
Delete the blank space. Thank you!

2022-11-03 10:40 UTC, stanciuvlad99 commented on src/test/java/AssigningModels/Base.java
> +
Delete the blank space. Thank you!

2022-11-03 10:40 UTC, stanciuvlad99 commented on src/test/java/AssigningModels/Base.java
> +
Delete the blank space. Thank you!

2022-11-03 10:40 UTC, stanciuvlad99 commented on src/test/java/AssigningModels/Base.java
> +
Delete the blank space. Thank you!

2022-11-03 10:40 UTC, stanciuvlad99 commented on src/test/java/AssigningModels/Tests.java
> +
Delete the blank space. Thank you!

2022-11-03 10:40 UTC, stanciuvlad99 commented on src/test/java/AssigningModels/Tests.java
> +
Delete the blank space. Thank you!

2022-11-03 17:16 UTC, pistamarcel approved these changes

2022-11-04 06:20 UTC, 95teo requested changes

2022-11-04 06:20 UTC, 95teo commented on src/main/java/utils/JavascriptUtils.java
> +    public final String scrollUntil = "arguments[0].scrollIntoView();";
Please stick to Java conventions when naming constants - caps with underscore between words -> SCROLL_INTO_VIEW_SCRIPT. Thanks!

2022-11-04 09:44 UTC, ElizaPopa commented on src/main/java/utils/JavascriptUtils.java
> +    public final String scrollUntil = "arguments[0].scrollIntoView();";
Roger that. I've changed. Thanks!

2022-11-04 11:19 UTC, 95teo approved these changes

2022-11-04 11:20 UTC, merged