Added Test Class
SkillBrain-com/Calisto-g1-15-05-22-internship-xretech pull request #4
Opened 2022-09-22 17:36 UTC by ElizaPopa

2022-10-06 14:44 UTC, 95teo requested changes

2022-10-06 14:44 UTC, 95teo commented on src/main/java/models/AccountDetails.java
> +    public String countryName;
Why is this public? It should be private too and be accessed via setter/getter only. Thanks!

2022-10-06 14:44 UTC, 95teo commented on src/main/java/pages/ClientRegistrationPage.java
> +
Please remove this unnecessary blank line. Thanks!

2022-10-06 14:44 UTC, 95teo commented on src/test/java/companyCountryRegistration/Tests.java
> +        Assert.assertTrue(urlSubs.equals("https://dev.xreteh.com/signup"), "The client wasn't properly redirected to the subscription's page");
This assertion will always be true. Please use getCurrentUrl() instead. Thanks!

2022-10-06 14:44 UTC, 95teo commented on src/test/java/companyCountryRegistration/Tests.java
> +
Please remove this unnecessary blank line. Thanks!

2022-10-06 14:44 UTC, 95teo commented on src/test/java/companyCountryRegistration/Tests.java
> +
Please remove this unnecessary blank line. Thanks!

2022-10-06 14:44 UTC, 95teo commented on src/test/java/companyCountryRegistration/Tests.java
> +
Please remove this unnecessary blank line. Thanks!

2022-10-06 14:44 UTC, 95teo commented on src/test/java/companyCountryRegistration/Tests.java
> +        Assert.assertTrue(errorMessage.equalsIgnoreCase(errorMessage), "Success registration with empty field");
This assertion will always be true. Please take one of the messages from a WebElement. Thanks!

2022-10-06 14:44 UTC, 95teo commented on src/test/java/companyCountryRegistration/Tests.java
> +        Assert.assertTrue(urlSubs.equals("https://dev.xreteh.com/signup"), "The client wasn't properly redirected to the subscription's page");
This assertion will always be true. Please use getCurrentUrl() instead. Thanks!

2022-10-06 14:44 UTC, 95teo commented on src/test/java/companyCountryRegistration/Tests.java
> +        Assert.assertFalse(Boolean.parseBoolean(urlSubs), "The client shouldn't have been created, there is a minimum of 30 characters that was exceeded");
What do you want to do here?

2022-10-06 14:44 UTC, 95teo commented on src/test/java/companyCountryRegistration/Tests.java
> +        Assert.assertEquals(errorMessageMinLengthCompany, errorMessageMinLengthCompany);
This assertion will always be true. Please take one of the messages from a WebElement. Thanks!

2022-10-06 14:44 UTC, 95teo commented on src/test/java/companyCountryRegistration/Tests.java
> +        Assert.assertEquals(errorMessageMinLengthName,errorMessageMinLengthName);
This assertion will always be true. Please take one of the messages from a WebElement. Thanks!

2022-10-06 14:44 UTC, 95teo commented on src/test/java/companyCountryRegistration/Tests.java
> +
Please remove this unnecessary blank line. Thanks!

2022-10-06 14:44 UTC, 95teo commented on .gitignore
> +/.idea
Try to avoid checking in files from target folder. Thanks!

2022-10-06 17:53 UTC, ElizaPopa commented on src/test/java/companyCountryRegistration/Tests.java
> +        Assert.assertFalse(Boolean.parseBoolean(urlSubs), "The client shouldn't have been created, there is a minimum of 30 characters that was exceeded");
Nici eu nu stiu exact ce am facut acolo, dar am refacut.

2022-10-06 17:57 UTC, ElizaPopa commented on src/test/java/companyCountryRegistration/Tests.java
> +        Assert.assertEquals(errorMessageMinLengthCompany, errorMessageMinLengthCompany);
done

2022-10-07 05:18 UTC, 95teo requested changes

2022-10-07 05:18 UTC, 95teo commented on src/main/java/models/AccountDetails.java
> +    private String emailAddress;
Can you please leave a line between fields and methods? Thanks!

2022-10-07 05:18 UTC, 95teo commented on src/main/java/modelsGenerator/AccountDetailsGenerator.java
> +package modelsGenerator;
Can you please reformat this file? Thanks!

2022-10-07 05:18 UTC, 95teo commented on src/main/java/modelsGenerator/AccountDetailsGenerator.java
> +    AccountDetails accountDetails;
Can you please leave a line between fields and methods? Thanks!

2022-10-07 05:18 UTC, 95teo commented on src/main/java/pages/ClientRegistrationPage.java
> +package pages;
Can you please reformat this file? Thanks!

2022-10-07 05:18 UTC, 95teo commented on src/main/java/pages/ClientRegistrationPage.java
> +    public void getFreeTrialSubscription(AccountDetails accountDetails) {
Please rename this method to clickOnFreeTrialButton(). Also, there is no need to put an AccountDetails parameter. Leave it parameter-less. Thanks!

2022-10-07 05:18 UTC, 95teo commented on src/test/java/companyCountryRegistration/Base.java
> +    AccountDetailsGenerator accountDetailsGenerator;
I'll put AccountDetailsGenerator and AccountDetails only in the test classes where they are used. We're going to have a common Base for all test classes and these AccountDetailsGenerator and AccountDetails won't be used everywhere. Thanks!

2022-10-07 05:18 UTC, 95teo commented on src/main/java/pages/ClientRegistrationPage.java
> +    public WebElement getErrorMessageForCompanyAdress() { return errorMessageForCompanyAdress; }
Please make these methods to return the text directly from here. No need to do that in the test case class. Thanks!
Applicable for all methods used to get some text/errorMessage

2022-10-07 05:18 UTC, 95teo commented on src/test/java/companyCountryRegistration/Tests.java
> +package companyCountryRegistration;
Have you reformated this file?

2022-10-07 07:35 UTC, ElizaPopa commented on src/main/java/pages/ClientRegistrationPage.java
> +package pages;
I've done this and it puts automatically one line break between methods. I hope i don't need to delete them again. :)

2022-10-07 08:08 UTC, ElizaPopa commented on src/main/java/pages/ClientRegistrationPage.java
> +    public WebElement getErrorMessageForCompanyAdress() { return errorMessageForCompanyAdress; }
done. Thanks for the hint! It looks better this way.

2022-10-07 08:10 UTC, ElizaPopa commented on src/test/java/companyCountryRegistration/Tests.java
> +package companyCountryRegistration;
I think so… do you refer from Code/ Reformat code, right?

2022-10-07 08:20 UTC, ElizaPopa commented on src/test/java/companyCountryRegistration/Base.java
> +    AccountDetailsGenerator accountDetailsGenerator;
Roger that and solved. Thanks!

2022-10-07 08:24 UTC, ElizaPopa commented on src/test/java/companyCountryRegistration/Tests.java
> +package companyCountryRegistration;
I've done also reformat line from Code Menu Button.

2022-10-07 08:34 UTC, 95teo requested changes

2022-10-07 08:34 UTC, 95teo commented on src/test/java/companyCountryRegistration/Tests.java
> +        accountDetailsGenerator = new AccountDetailsGenerator();
This line should be above the previous one. Please check for all methods on this test class. Thanks!

2022-10-07 08:37 UTC, ElizaPopa commented on src/test/java/companyCountryRegistration/Tests.java
> +        accountDetailsGenerator = new AccountDetailsGenerator();
done

2022-10-07 08:43 UTC, 95teo approved these changes

2022-10-07 14:26 UTC, pistamarcel approved these changes

2022-10-10 05:59 UTC, merged