Stanciu vlad/sm tm 5cd2f Manage Default Subscriptions
SkillBrain-com/Calisto-g1-15-05-22-internship-xretech pull request #5
Opened 2022-09-27 17:36 UTC by stanciuvlad99

2022-09-28 16:13 UTC, 95teo requested changes

2022-09-28 16:13 UTC, 95teo commented on src/test/java/xertechTests/ManageDefaultSubscriptionsTest.java
> +        assertTrue(driver.getCurrentUrl().contains("subscription-plans"),
You could add a method in BasePage that return driver.getCurrentUrl() and use it in your tests. In this way, you'll minimize direct interaction with Selenium related methods in test cases classes. Thanks!

2022-09-28 16:13 UTC, 95teo commented on src/test/java/xertechTests/ManageDefaultSubscriptionsTest.java
> +//        assertEquals(manageDefaultSubscriptionsPage.getNameTest().getText(), "Free trial", "Error");
Why is this line commented?

2022-09-28 16:13 UTC, 95teo commented on src/test/java/xertechTests/ManageDefaultSubscriptionsTest.java
> +        manageDefaultSubscriptionsPage.loginAdmin("tammyvu@longdz.site", "hqlyz4oi");
Since you already added email and password in config file you can use them from there via configProperty.getProperty("usernameSupportXertech") and configProperty.getProperty("passwordSupportXertech"). Thanks!

2022-09-28 16:13 UTC, 95teo commented on src/test/java/xertechTests/ManageDefaultSubscriptionsTest.java
> +        assertTrue(driver.getCurrentUrl().contains("/62e2709c9d455ed2a4217c21"),
You could add a method in BasePage that return driver.getCurrentUrl() and use it in your tests. In this way, you'll minimize direct interaction with Selenium related methods in test cases classes. Thanks!

2022-09-28 16:13 UTC, 95teo commented on src/test/java/xertechTests/ManageDefaultSubscriptionsTest.java
> +        assertTrue(driver.getCurrentUrl().contains("/632f365cadb2be493ed280d2"),
You could add a method in BasePage that return driver.getCurrentUrl() and use it in your tests. In this way, you'll minimize direct interaction with Selenium related methods in test cases classes. Thanks!

2022-09-28 16:13 UTC, 95teo commented on src/main/java/pages/ManageDefaultSubscriptionsPage.java
> +    public void loginAdmin(String username, String password){
Please rename it to loginWithCredentials(String username, String password). It has a more meaningful name like this as it could be used for multiple users. Thanks!

2022-09-28 16:13 UTC, 95teo commented on src/main/java/pages/ManageDefaultSubscriptionsPage.java
> +package pages;
Please reformat code on this file. Thanks!

2022-09-29 06:12 UTC, 95teo requested changes

2022-09-29 06:12 UTC, 95teo commented on src/main/java/pages/ManageDefaultSubscriptionsPage.java
> +        getFreeTrialMonthlyPriceInput().sendKeys(Keys.CONTROL, "a");
Use WebElement instead of function for both occurrences. Thanks!

2022-09-29 06:12 UTC, 95teo commented on src/test/java/xertechTests/Base.java
> +
Please remove this extra blank line. Thanks!

2022-09-29 06:12 UTC, 95teo commented on src/test/java/xertechTests/Base.java
> +package xertechTests;
Can you please move this class to test/java package to be used by all test classes? Thanks!

2022-09-29 06:12 UTC, 95teo commented on src/test/java/xertechTests/Base.java
> +        url = configProperty.getProperty("urlXertech");
Let's consider to add an Enum with constants for these properties from config files for easier maintenance. Thanks!

2022-09-29 06:12 UTC, 95teo commented on src/test/java/xertechTests/ManageDefaultSubscriptionsTest.java
> +    public void SubscriptionPlansManagedByAdmin() {
Please use camelCase when naming methods. Thanks!
Applicable for all methods from this class.

2022-09-29 06:12 UTC, 95teo commented on src/test/java/xertechTests/ManageDefaultSubscriptionsTest.java
> +
Please remove one blank line. Thanks!

2022-09-29 06:12 UTC, 95teo commented on src/test/java/xertechTests/ManageDefaultSubscriptionsTest.java
> +
Please remove this blank line. Thanks!

2022-09-29 06:12 UTC, 95teo commented on src/test/java/xertechTests/ManageDefaultSubscriptionsTest.java
> +        Thread.sleep(2000);
Instead of using sleep, try to make a method for waiting the page to load. Thanks!

2022-09-29 06:12 UTC, 95teo commented on src/test/java/xertechTests/ManageDefaultSubscriptionsTest.java
> +
Please remove on blank line. Thanks!

2022-09-29 06:12 UTC, 95teo commented on src/test/java/xertechTests/ManageDefaultSubscriptionsTest.java
> +        Thread.sleep(2000);
Instead of using sleep, try to make a method for waiting the page to load. Thanks!

2022-09-29 06:12 UTC, 95teo commented on src/test/java/xertechTests/ManageDefaultSubscriptionsTest.java
> +        fluentWait(driver).until(ExpectedConditions.visibilityOfElementLocated(By.id("subscriptionPlan-diskQuota")));
To consider using a WaitUtils class instead of using this method directly in test case. Thanks!

2022-10-06 08:55 UTC, 95teo requested changes

2022-10-06 08:55 UTC, 95teo commented on pom.xml
> +            <version>4.5.0</version>
Is this change really needed?

2022-10-06 08:55 UTC, 95teo commented on src/main/java/implementation/BrowserManager.java
> +import org.openqa.selenium.chrome.ChromeOptions;
I don't see any usages for this import. Please remove it. Thanks!

2022-10-06 08:55 UTC, 95teo commented on src/main/java/pages/BasePage.java
> +    public static String url(){
Please rename this method to getCurrentUrl(). It has more meaning instead of url(). Also remove static part. Thanks!

2022-10-07 15:14 UTC, pistamarcel approved these changes

2022-10-10 06:05 UTC, 95teo commented
You'll need to fix the conflicts first. Thanks!

2022-10-11 18:29 UTC, 95teo requested changes

2022-10-11 18:29 UTC, 95teo commented on src/main/java/pages/BasePage.java
> +    static WebDriver driver = null;
Please leave it as final as it was before. No need to make it static. Thanks!

2022-10-11 18:29 UTC, 95teo commented on src/main/java/pages/BasePage.java
> +    public static String getCurrentUrl(){
Please remove static from method signature. Thanks!

2022-10-11 18:29 UTC, 95teo commented on src/main/java/pages/ManageDefaultSubscriptionsPage.java
> +
Please remove this empty line. Thanks!

2022-10-11 18:29 UTC, 95teo commented on src/main/java/models/UserCredential.java
> +
Please remove one empty line. Thanks!

2022-10-11 18:29 UTC, 95teo commented on config/config.properties
> +pollingInterval = 500
Please leave one empty line at the end of each file. Thanks!

2022-10-11 18:29 UTC, 95teo commented on src/main/java/pages/ManageDefaultSubscriptionsPage.java
> +    public void addToMonthlyPrice(){
You have already a method for doing this action -> writeTextOnMonthlyPrice(). Can you please delete this one?

2022-10-11 18:29 UTC, 95teo commented on src/main/java/pages/ManageDefaultSubscriptionsPage.java
> +package pages;
Try to reformat again all of this file. Thanks!

2022-10-11 18:29 UTC, 95teo commented on src/main/java/utils/enums/ConfigPropertiesEnum.java
> +    public enum ConfigPropertiesEnum {
Please don't forget to add the other used properties from config file and replace string occurrences with enum's value. Thanks!

2022-10-11 18:29 UTC, 95teo commented on src/test/java/xertechTests/Base.java
> +package xertechTests;
Can you please move this class to test/java package to be used by all test classes? Thanks!

2022-10-11 18:29 UTC, 95teo commented on src/test/java/xertechTests/ManageDefaultSubscriptionsTest.java
> +    @Test
Please leave an extra blank line between class name and @Test annotation. Thanks!

2022-10-11 18:29 UTC, 95teo commented on src/test/java/xertechTests/ManageDefaultSubscriptionsTest.java
> +        assertTrue(manageDefaultSubscriptionsPage.getCurrentUrl().contains("subscription-plans"),
Can you please add "subscription-plans" to a constant and use it instead of hardcoded string? Thanks!

2022-10-13 04:04 UTC, 95teo commented on src/test/java/xertechTests/ManageDefaultSubscriptionsTest.java
> +        assertTrue(manageDefaultSubscriptionsPage.getCurrentUrl().contains("subscription-plans"));
You missed to replace this "subscription-plans" with the created variable. Please address it into the next PR. Thanks!

2022-10-13 04:05 UTC, 95teo approved these changes

2022-10-13 04:33 UTC, merged