Liviu popa/sm tm e1e56 crud all categories and subcategories
SkillBrain-com/Calisto-g1-15-05-22-internship-xretech pull request #7
Opened 2022-09-29 06:17 UTC by livpopa

Added Base and Tests Class

2022-09-29 07:49 UTC, 95teo commented on src/test/java/crudAllCaterogiesAndSubcategoriesTests/Base.java
> +package crudAllCaterogiesAndSubcategoriesTests;
You have a typo in the name of the package. Please change package name _crudAllCaterogiesAndSubcategoriesTests_ -> **crudAllCategoriesAndSubcategoriesTests**. Thanks!

2022-09-29 07:59 UTC, livpopa commented on src/test/java/crudAllCaterogiesAndSubcategoriesTests/Base.java
> +package crudAllCaterogiesAndSubcategoriesTests;
hi Teo. I believe i did the change. Could you please double check?

2022-10-18 17:04 UTC, 95teo commented on src/main/java/pages/CategoriesPage.java
> +
Please remove one blank line. Thanks!

2022-10-18 17:08 UTC, 95teo commented on src/main/java/pages/CategoriesPage.java
> +
Please remove one blank line. Thanks!

2022-10-18 17:09 UTC, 95teo approved these changes

2022-10-18 17:09 UTC, 95teo commented on src/main/java/pages/CategoriesPage.java
> +
Please remove one blank line. Thanks!

2022-10-18 17:11 UTC, 95teo commented on src/main/java/pages/CategoriesPage.java
> +
Please remove one blank line. Thanks!

2022-11-04 06:22 UTC, 95teo commented
Don't forget to fix the conflicts. Thanks!

2022-11-04 09:00 UTC, 95teo requested changes

2022-11-06 07:10 UTC, 95teo requested changes

2022-11-06 07:10 UTC, 95teo commented on src/test/java/crudAllCategoriesAndSubcategoriesTests/Tests.java
> +        driver.quit();
I was refferring to add the @AfterMethod/@AfterSuite methods like in the other Base test classes from other packages. Not putine this line at test level. Thanks!

2022-11-07 12:24 UTC, 95teo approved these changes

2022-11-08 18:08 UTC, ElizaPopa approved these changes

2022-11-08 18:08 UTC, ElizaPopa commented on src/main/java/modelsGenerator/CategoryDetailsGenerator.java
> +
Please delete this blank line. Thank you.

2022-11-09 08:19 UTC, merged