first commit
SkillBrain-com/Calisto-g1-15-05-22-internship-xretech pull request #8
Opened 2022-09-29 15:50 UTC by pistamarcel

First try task SM-TM-dc1dc

2022-10-03 13:58 UTC, 95teo commented
Please don't check in .idea, target and test-output folders. Thanks!

2022-10-03 14:17 UTC, 95teo requested changes

2022-10-03 14:17 UTC, 95teo commented on config/config.properties
> +urlXertech= https://dev.xreteh.com/login
Please reformat this file, thanks!

2022-10-03 14:17 UTC, 95teo commented on src/main/java/implementation/ElementControl.java
> +
Please remove these empty lines! Thanks!

2022-10-03 14:17 UTC, 95teo commented on src/main/java/implementation/ElementControl.java
> +import org.openqa.selenium.By;
I don't think you've used these imports, so please remove them. Thanks!

2022-10-03 14:17 UTC, 95teo commented on src/main/java/pages/LoginXrPage.java
> +    public WebElement getLoginEmail() {
getLoginEmail(), getPasswordInput() and getLoginButton()  are not used so please remove them. Thanks!

2022-10-03 14:17 UTC, 95teo commented on src/main/java/pages/ManageSubscriptionsAsASupportUserPage.java
> +    public WebElement getClientsBtnPage() {
Please remove not used getter methods. Thanks!

2022-10-03 14:17 UTC, 95teo commented on src/main/java/pages/ManageSubscriptionsAsASupportUserPage.java
> +    public WebElement getSubscriptonDetailsStartDate() throws InterruptedException {
Typo in the name of method Subscripton -> Subscription

2022-10-03 14:17 UTC, 95teo commented on src/main/java/pages/ManageSubscriptionsAsASupportUserPage.java
> +        Thread.sleep(1000);
Try to use a fluentWait instead of Thread.sleep(). Thanks! You can use as reference @stanciuvlad99 PR #5 :D

2022-10-03 14:17 UTC, 95teo commented on src/main/java/pages/ManageSubscriptionsAsASupportUserPage.java
> +    public WebElement getisActive() throws InterruptedException {
Please use camelCase when naming methods as per Java conventions. Thanks!

2022-10-03 14:17 UTC, 95teo commented on src/main/java/pages/ManageSubscriptionsAsASupportUserPage.java
> +
Please remove all of these extra blank lines from the end of file. Thanks!

2022-10-03 14:17 UTC, 95teo commented on src/test/java/xertechTests/Base.java
> +
Please remove on blank line. Thanks!

2022-10-03 14:17 UTC, 95teo commented on src/test/java/xertechTests/Base.java
> +
Please remove on blank line. Thanks!

2022-10-03 14:17 UTC, 95teo commented on src/test/java/xertechTests/Base.java
> +}
Please add a blank line at the end of file. Thanks!

2022-10-03 14:17 UTC, 95teo commented on src/test/java/xertechTests/manageSubscriptionAsSupportUserTest.java
> +public class manageSubscriptionAsSupportUserTest  extends Base {
Class names start with capital letter in Java. Please make this change too. Thanks!

2022-10-03 14:17 UTC, 95teo commented on src/test/java/xertechTests/manageSubscriptionAsSupportUserTest.java
> +        System.out.println("****************************************" + manageSubscriptionsAsASupportUserPage.getConfirmTransferBtnText().getText());
Please remove these System.out.println() lines if they we're used for debugging and replace them with logger.info(). Thanks!

2022-10-10 06:14 UTC, 95teo commented
You'll need to fix the conflicts first. Thanks!

2022-10-10 14:25 UTC, 95teo requested changes

2022-10-10 14:25 UTC, 95teo commented on src/main/java/pages/LoginXrPage.java
> +    @FindBy(css = "input[placeholder=\"Password\"]")
Can you please change inside strings for selectors the double quotes (") to single quote (') and remove escape characters(**** or /)? Escape characters (\ or /) might cause some issues on different operating systems. Thanks!
For example, @FindBy(css = "input[placeholder=\"Password\"]") -> @FindBy(css = "input[placeholder='Password']")

Applicable for all elements that have double quotes (") inside strings in all classes.

2022-10-10 14:25 UTC, 95teo commented on src/main/java/pages/ManageSubscriptionsAsASupportUserPage.java
> +    @FindBy(css = "li.rounded-lg.mb-2 a[href=\"/clients\"]")
Same comment for this class.

2022-10-10 14:25 UTC, 95teo commented on src/test/java/manageSubscriptionsAsASupport/ManageSubscriptionAsSupportUserTest.java
> +        fluentWait(driver).until(ExpectedConditions.numberOfElementsToBeMoreThan(By.cssSelector("div[data-field=\"actions\"]"),10));
Can you please move this into a method in the page and not use it directly in test case? Thanks!
Applicable for others fluentWait occurrences too.

2022-10-10 14:25 UTC, 95teo commented on src/test/java/manageSubscriptionsAsASupport/Base.java
> +    protected FluentWait<WebDriver> fluentWait(WebDriver driver) {
Can you please move this method in the BasePage instead? Thanks!

2022-10-10 14:25 UTC, 95teo commented on src/test/java/manageSubscriptionsAsASupport/Base.java
> +    protected boolean isElementPresent(By locator) {
Can you please move this method in the BasePage instead? Thanks!

2022-10-11 11:09 UTC, 95teo requested changes

2022-10-12 09:41 UTC, 95teo requested changes

2022-10-12 09:41 UTC, 95teo commented on src/main/java/utils/WaitUtils.java
> +    private final WebDriver driver;
You shouldn't need this WebDriver. Please remove it. Thanks!

2022-10-12 09:41 UTC, 95teo commented on src/main/java/utils/WaitUtils.java
> +        new FluentWait(driver).until(ExpectedConditions.numberOfElementsToBeMoreThan(locator, number));
You should be able to use fluentWait.until(ExpectedConditions.numberOfElementsToBeMoreThan(locator, number));
Applicable for all methods from below.

2022-10-12 09:41 UTC, 95teo commented on src/test/java/manageSubscriptionsAsASupport/ManageSubscriptionAsSupportUserTest.java
> +        waitUtils.waitForTextToBe(By.cssSelector("h3[class='text-center']"), "Something went wrong");
Please add also this selector into a constant. Thanks!

2022-10-12 11:05 UTC, pistamarcel commented on src/main/java/utils/WaitUtils.java
> +    private final WebDriver driver;
I do need that final Webdriver or my fluentWait won't work :(.

2022-10-12 13:25 UTC, 95teo commented on src/main/java/utils/WaitUtils.java
> +    private final WebDriver driver;
Actually, it shouldn't. After you fix https://github.com/SkillBrain-com/Calisto-g1-15-05-22-internship-xretech/pull/8#discussion_r993221636 you should be fine with this asked change.

2022-10-12 13:25 UTC, 95teo commented on src/main/java/utils/WaitUtils.java
> +        new FluentWait(driver).until(ExpectedConditions.numberOfElementsToBeMoreThan(locator, number));
This was not solved yet.

2022-10-12 13:29 UTC, 95teo requested changes

2022-10-12 13:29 UTC, 95teo commented on src/main/java/implementation/ElementControl.java
> +    public boolean isElementPresent(WebDriver driver, By locator) {
You shouldn't need to send WebDriver as parameter. You have the 'driver' field declared inside the class.

2022-10-12 15:03 UTC, pistamarcel commented on src/main/java/implementation/ElementControl.java
> +    public boolean isElementPresent(WebDriver driver, By locator) {
Asa m-am gandit si eu dar daca nu il dau imi da driver null error.

2022-10-12 20:50 UTC, pistamarcel commented on src/main/java/utils/WaitUtils.java
> +        new FluentWait(driver).until(ExpectedConditions.numberOfElementsToBeMoreThan(locator, number));
I think its done.

2022-10-13 04:26 UTC, 95teo requested changes

2022-10-13 04:26 UTC, 95teo commented on src/main/java/implementation/ElementControl.java
> +    public boolean isElementPresent(WebDriver driver, By locator) {
There should be another reason for that null driver. There are plenty of methods in this class that use WebDriver and are working fine. If you can't figure it out let's discuss in today's meeting. Thanks!

2022-10-13 04:26 UTC, 95teo commented on src/main/java/utils/WaitUtils.java
> +        new FluentWait(driver).until(ExpectedConditions.numberOfElementsToBeMoreThan(locator, number));
Nope, it's not :D I was referring to replace the line new FluentWait(driver).until(ExpectedConditions.numberOfElementsToBeMoreThan(locator, number)); with -> fluentWait.until(ExpectedConditions.numberOfElementsToBeMoreThan(locator, number));
You also deleted the other two methods that were previously in this class. Was this intended?

2022-10-14 06:00 UTC, 95teo requested changes

2022-10-16 15:25 UTC, 95teo approved these changes

2022-10-17 18:29 UTC, stanciuvlad99 approved these changes

2022-10-17 18:29 UTC, stanciuvlad99 commented on src/main/java/pages/ManageSubscriptionsAsASupportUserPage.java
> +    private WebElement supportUserBtnPage;
Add a blank space here. Thank you!

2022-10-17 18:29 UTC, stanciuvlad99 commented on src/main/java/pages/ManageSubscriptionsAsASupportUserPage.java
> +    private List<WebElement> clientsButtonList;
Add a blank space here. Thank you!

2022-10-17 18:29 UTC, stanciuvlad99 commented on src/main/java/pages/ManageSubscriptionsAsASupportUserPage.java
> +    private WebElement endUserIsActiveBtn;
Add a blank space here. Thank you!

2022-10-17 18:29 UTC, stanciuvlad99 commented on src/main/java/pages/ManageSubscriptionsAsASupportUserPage.java
> +
Remove a blank space here. Thank you!

2022-10-17 18:29 UTC, stanciuvlad99 commented on src/main/java/pages/ManageSubscriptionsAsASupportUserPage.java
> +    private WebElement modelToBeDeleted;
Add a blank space here. Thank you!

2022-10-17 18:29 UTC, stanciuvlad99 commented on src/main/java/pages/ManageSubscriptionsAsASupportUserPage.java
> +    private WebElement removeBtn;
Add a blank space here. Thank you!

2022-10-17 18:29 UTC, stanciuvlad99 commented on src/main/java/pages/ManageSubscriptionsAsASupportUserPage.java
> +    private WebElement isAlertMessage;
Add a blank space here. Thank you!

2022-10-17 18:29 UTC, stanciuvlad99 commented on src/main/java/pages/ManageSubscriptionsAsASupportUserPage.java
> +    private List<WebElement> assignModelButton;
Add a blank space here. Thank you!

2022-10-17 18:29 UTC, stanciuvlad99 commented on src/main/java/pages/ManageSubscriptionsAsASupportUserPage.java
> +
Remove a blank space here. Thank you!

2022-10-17 18:29 UTC, stanciuvlad99 commented on src/main/java/pages/ManageSubscriptionsAsASupportUserPage.java
> +
Remove a blank space here. Thank you!

2022-10-17 18:29 UTC, stanciuvlad99 commented on src/main/java/utils/WaitUtils.java
> +
Remove a blank space here. Thank you!

2022-10-17 18:29 UTC, stanciuvlad99 commented on src/test/java/manageSubscriptionsAsASupport/Base.java
> +
Remove 2 and 3 lines space here. Thank you!

2022-10-17 18:29 UTC, stanciuvlad99 commented on src/test/java/manageSubscriptionsAsASupport/Base.java
> +
Remove a blank space here. Thank you!

2022-10-17 18:29 UTC, stanciuvlad99 commented on src/test/java/manageSubscriptionsAsASupport/ManageSubscriptionAsSupportUserTest.java
> +
Remove a blank space here. Thank you!

2022-10-17 18:29 UTC, stanciuvlad99 commented on src/test/java/manageSubscriptionsAsASupport/ManageSubscriptionAsSupportUserTest.java
> +
Remove a blank space here. Thank you!

2022-10-17 18:29 UTC, stanciuvlad99 commented on src/test/java/manageSubscriptionsAsASupport/ManageSubscriptionAsSupportUserTest.java
> +        assertNotEquals(before, after, "Starea userului a ramas aceeasi dupa incearcarea noastra de a o schimba");
Choose only one language, Romanian or English.

2022-10-17 18:29 UTC, stanciuvlad99 commented on src/test/java/manageSubscriptionsAsASupport/ManageSubscriptionAsSupportUserTest.java
> +        assertNotEquals(before, after, "Starea userului a ramas aceeasi dupa incearcarea noastra de a o schimba");
Choose only one language, Romanian or English.

2022-10-17 18:29 UTC, stanciuvlad99 commented on src/test/java/manageSubscriptionsAsASupport/ManageSubscriptionAsSupportUserTest.java
> +                "Nu ni se afiseaza butonul done desi am salvat schimbarile cu privire la starea de activitate a user-ului");
Choose only one language, Romanian or English.

2022-10-17 20:30 UTC, merged