Silviu stan/sm tm 0eadd select a subscription plan
SkillBrain-com/Calisto-g1-15-05-22-internship-xretech pull request #9
Opened 2022-10-11 16:48 UTC by SvSilviu

2022-10-12 09:59 UTC, 95teo requested changes

2022-10-12 09:59 UTC, 95teo commented on src/main/java/pages/SubscriptionPlanPage.java
> +    public void clickOnCreateAccountBtn() {
Please move methods after WebElements meaning that you first will put WebElements grouped and then the methods after WebElements. Thanks!

2022-10-12 09:59 UTC, 95teo commented on src/main/java/pages/SubscriptionPlanPage.java
> +    @FindBy(xpath = "//*[@id=\"root\"]/div/div/div[1]/form/div[3]/a[1]")
Can you please change inside strings for selectors the double quotes (") to single quote (') and remove escape characters(**** or /)? Escape characters (\ or /) might cause some issues on different operating systems. Thanks!
For example, @FindBy(xpath = "//*[@id=\"root\"]/div/div/div[1]/form/div[3]/a[1]") -> @FindBy(xpath = "//*[@id='root']/div/div/div[1]/form/div[3]/a[1]")

Applicable for all elements that have double quotes (") inside strings.

2022-10-14 06:04 UTC, 95teo requested changes

2022-10-14 06:04 UTC, 95teo commented on src/main/java/pages/SubscriptionPlanPage.java
> +
No need to have two blank lines here. Leave only one. Thanks!

2022-10-14 06:04 UTC, 95teo commented on src/test/java/subscriptionPlanWhenRegisteringTests/SubscriptionPlanTests.java
> +
No need to leave a blank line between last line of a method and }. You can remove it. Applicable for all tests. Thanks!
Same comment for first blank line inside the method.

2022-10-18 17:47 UTC, 95teo approved these changes

2022-10-27 16:10 UTC, stanciuvlad99 approved these changes

2022-10-28 12:04 UTC, merged